## Importar Librerías

In [7]:
import numpy as np

### Crear lista de código de 0 a 10 (Esto no es un array u objeto de numpy)

In [3]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

## Crear arrays desde numpy

In [9]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## Crear un array de ceros
##### Sirve para definir esquemas previos

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

### Crear un esquema previo de unos

In [14]:
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### Crear esquema especificando desde donde inicia, hasta donde termina y cuántos datos se quiere generar

In [15]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

### Función eye (Creación de una matriz con diagonal principal en 1 y el resto en 0)

In [16]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Creación de valores aleatorios

In [18]:
np.random.rand()

0.0008974791942776283

In [19]:
np.random.rand(4)

array([0.47574766, 0.82957337, 0.99750607, 0.71019416])

In [20]:
np.random.rand(4,4)

array([[0.37866074, 0.90156913, 0.98238763, 0.74362039],
       [0.79251372, 0.80496407, 0.1500285 , 0.88039005],
       [0.11073957, 0.79466983, 0.97113064, 0.92584481],
       [0.02643018, 0.69137984, 0.11087938, 0.70983613]])

### Generar un entero aleatorio

In [24]:
np.random.randint(1,15)

7

### Generar matrices aleatorias

In [23]:
np.random.randint(1,100,(10,10))

array([[ 4, 60, 14, 59, 22, 34, 14, 95, 66, 32],
       [42, 39, 96, 50, 79,  5, 68, 85, 36, 58],
       [67, 55, 69, 51, 57, 28, 89,  3, 48, 67],
       [86, 91, 38,  2, 42, 41, 15,  4, 25, 81],
       [81, 94, 65, 88, 11, 57, 45, 64, 74, 32],
       [13, 96, 97, 51, 91, 68, 23, 69, 65, 94],
       [24, 42, 56, 91, 99,  5, 98, 89, 80, 98],
       [59,  2, 21, 71, 70, 82, 39, 19, 55, 91],
       [91, 11,  4, 59, 52, 68, 21, 96, 80, 12],
       [99, 61, 56, 22, 71, 31, 53, 62, 31, 18]])