## Importar Librería

In [3]:
import numpy as np

## Definiendo Arrays

In [6]:
scalar = np.array(42)
print(scalar)
scalar.ndim

42


0

In [7]:
vector = np.array([1,2,3])
print(vector)
vector.ndim

[1 2 3]


1

In [10]:
matriz = np.array([[1,2,3],[4,5,6],[7,8,9],[10,12,63]])
print(matriz)
matriz.ndim

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 12 63]]


2

In [11]:
tensor = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,12,63]],[[7,5,3],[9,5,4],[3,7,9],[15,17,35]]])
print(tensor)
tensor.ndim

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 12 63]]

 [[ 7  5  3]
  [ 9  5  4]
  [ 3  7  9]
  [15 17 35]]]


3

## Agregar o Eliminar dimensiones

In [13]:
vector = np.array([1,2,3], ndmin=10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [14]:
expand = np.expand_dims(np.array([1,2,3]), axis=0)
print(expand)
expand.ndim

[[1 2 3]]


2

In [18]:
print(vector, vector.ndim)
vector_2 = np.squeeze(vector)
print(vector_2, vector_2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1
