### Importando librerías

In [1]:
import numpy as np

### Generar array de números aleatorios

In [2]:
arr = np.random.randint(1,10,(3,2))

In [3]:
arr

array([[5, 1],
       [4, 7],
       [7, 6]])

### Conocer la forma del array definido

In [4]:
arr.shape

(3, 2)

### Cambiar la forma establecida de un array

In [5]:
arr.reshape(1,6)

array([[5, 1, 4, 7, 7, 6]])

In [6]:
arr.reshape(2,3)

array([[5, 1, 4],
       [7, 7, 6]])

In [7]:
np.reshape(arr,(1,6))

array([[5, 1, 4, 7, 7, 6]])

### Ordenación

In [8]:
np.reshape(arr, (2,3), 'C')

array([[5, 1, 4],
       [7, 7, 6]])

In [9]:
np.reshape(arr, (2,3), 'F')

array([[5, 7, 7],
       [4, 1, 6]])

In [10]:
np.reshape(arr, (2,3), 'A')

array([[5, 1, 4],
       [7, 7, 6]])